### ISSUE TITLE
[Tracker] Collection tagging policy violations

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#223]
I plan to use this issue as a tracker for collections that need to be pinned to an earlier release due to not tagging releases in their respective Github repositories.

More to come!

**Comment by gotmax23** [comment]
cyberark.pas is *again* violating this guideline (https://github.com/ansible-community/ansible-build-data/pull/235#issuecomment-1556293107).

**Comment by felixfontein** [comment]
dellemc.enterprise_sonic needs to be pinned to 2.0.0 in both Ansible 7 and Ansible 8 for two violations:
- (applies only to Ansible 8) https://github.com/ansible-community/ansible-build-data/issues/223
- (applies to both Ansible 7 and 8) https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/268

**Comment by felixfontein** [comment]
There has been a new release of dellemc.enterprise_sonic (2.2.0) which reverts the breaking change and declares compatibility with `ansible.netcommon` `>5.0.0`. This fixes the problems with Ansible 8 (except that the breaking change will still be mentioned in the next porting guide, even though it is no longer a breaking change - I guess we have to add an Ansible changelog entry for that), but has the downside of not allowing this release for the next Ansible 7 release since that one has ansible.netcommon 4.x.y. So we have to keep the pin for Ansible 7 (though now it has another reason), and undo it (with a changelog entry) for Ansible 8.

**Comment by felixfontein** [comment]
The issue with hetzner.hcloud is resolved (https://github.com/ansible-collections/hetzner.hcloud/issues/217, #267).

**Comment by gotmax23** [comment]
> inspur.ispim 2.0.1 is not tagged in https://github.com/ispim/inspur.ispim

https://github.com/ispim/inspur.ispim/issues/24

**Comment by felixfontein** [comment]
- cisco.intersight 2.0.2 is not tagged in https://github.com/CiscoDevNet/intersight-ansible
- cisco.meraki 2.16.0 is not tagged in https://github.com/CiscoDevNet/ansible-meraki

**Comment by felixfontein** [comment]
cisco.meraki moved to a new repository: https://github.com/meraki/dashboard-api-ansible - I'll create PRs for ansible-build-data to adjust it.

**Comment by felixfontein** [comment]
cisco.intersight was now tagged, #289 removed the ignore for the missing tags.

**Comment by felixfontein** [comment]
- https://github.com/ansible-collections/netapp.aws/issues/8
- https://github.com/ansible-collections/netapp.azure/issues/8
- https://github.com/ansible-collections/netapp.cloudmanager/issues/9
- https://github.com/ansible-collections/netapp.um_info/issues/10

**Comment by felixfontein** [comment]
- fortinet.fortios 2.3.4 is not tagged in https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection: https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/277

**Comment by gotmax23** [comment]
- purestorage.flasharray 1.22.0 contains [Breaking Changes](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/CHANGELOG.rst#breaking-changes-porting-guide)

**Comment by gotmax23** [comment]
https://github.com/Pure-Storage-Ansible/FlashArray-Collection/issues/500

**Comment by sdodsley** [comment]
> [Pure-Storage-Ansible/FlashArray-Collection#500](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/issues/500)

Resolved - poor usage of flag in the changelog. Changelogs fixed and new Collection version released

**Comment by gotmax23** [comment]
```
ERROR: found collection dependency errors!
ERROR: cisco.ise 2.6.2 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
ERROR: cisco.dnac 6.8.1 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
ERROR: cisco.meraki 2.16.16 version_conflict: ansible.utils-3.0.0 but needs >=2.0.0,<3.0
```

**Comment by gotmax23** [comment]
- cisco.meraki: https://github.com/meraki/dashboard-api-ansible/issues/38
- cisco.dnac: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/133
- cisco.ise: https://github.com/CiscoISE/ansible-ise/issues/112

**Comment by felixfontein** [comment]
- cisco.dnac 6.10.0 is not tagged: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/142
- ibm.storage_virtualize 2.2.0 is not tagged: https://github.com/ansible-collections/ibm.storage_virtualize/issues/36

**Comment by felixfontein** [comment]
- infinidat.infinibox 1.4.0 is not tagged: https://github.com/Infinidat/ansible-infinidat-collection/issues/20

**Comment by felixfontein** [comment]
- `ERROR: cisco.dnac 6.13.1 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0`: https://github.com/cisco-en-programmability/dnacenter-ansible/issues/160
- `ERROR: cisco.meraki 2.17.2 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0`: https://github.com/meraki/dashboard-api-ansible/issues/49
- `ERROR: cisco.ise 2.8.0 version_conflict: ansible.utils-4.0.0 but needs >=2.0.0,<4.0`: https://github.com/CiscoISE/ansible-ise/issues/123

**Comment by felixfontein** [comment]
community.ciscosmb introduced a breaking change in 1.0.8: https://github.com/ansible-collections/community.ciscosmb/issues/75

**Comment by mariolenz** [comment]
It looks like [frr.frr](https://github.com/ansible-collections/frr.frr) fails a lot of tests. I don't care about the unit tests but the failing sanity tests are problematic. I've opened ansible-collections/frr.frr#66 to let them know.

**Comment by mariolenz** [comment]
community.ciscosmb introduced a breaking change (removed feature) in 1.9.0: ansible-collections/community.grafana#367

**Comment by felixfontein** [comment]
cyberark.pas 1.0.27 is not tagged: https://github.com/cyberark/ansible-security-automation-collection/issues/71

**Comment by felixfontein** [comment]
It's too late for version pinning since 2.6.0 of that collection has been included for some months now, but FYI: https://github.com/CiscoDevNet/ansible-mso/issues/479

**Comment by felixfontein** [comment]
ansible.posix 1.6.0 has a breaking change (https://github.com/ansible-collections/ansible.posix/issues/463#issuecomment-2400499803). #469 restricts it to < 1.6.0 for Ansible 9 and 10. For Ansible 11, we have to see what happens.

**Comment by felixfontein** [comment]
cisco.dnac, cisco.meraki, and cisco.ise still require ansible.utils < 5.0.0 (pinned in #480 for Ansible 11).

**Comment by mariolenz** [comment]
cisco.dnac 6.24.0 isn't tagged: cisco-en-programmability/dnacenter-ansible#205

I suggest to wait a few days until we introduce a restriction. Maybe they'll fix this soon.

**Comment by felixfontein** [comment]
The problem has been resolved, the release is now tagged.

**Comment by felixfontein** [comment]
cisco.meraki 2.20.0 fails the compilation test due to bad indentation in a Python file: https://github.com/meraki/dashboard-api-ansible/issues/76

**Comment by felixfontein** [comment]
check_point.mgmt 6.3.0 is not tagged: https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/issues/164

**Comment by felixfontein** [comment]
ibm.storage_virtualize 2.7.2 is not tagged: https://github.com/ansible-collections/ibm.storage_virtualize/issues/57

**Comment by mariolenz** [comment]
> ibm.storage_virtualize 2.7.2 is not tagged: [ansible-collections/ibm.storage_virtualize#57](https://github.com/ansible-collections/ibm.storage_virtualize/issues/57)

As far as I can see, they don't even have the correct version in `galaxy.yml` in their repo 😲

**Comment by gotmax23** [comment]
- [ ] https://github.com/cisco-en-programmability/dnacenter-ansible/issues/254
- [ ] https://github.com/CiscoISE/ansible-ise/issues/156
- [ ] https://github.com/meraki/dashboard-api-ansible/issues/105

(https://github.com/ansible-community/ansible-build-data/pull/528)

**Comment by mariolenz** [comment]
grafana.grafana 6.0.0 is not tagged: grafana/grafana-ansible-collection#345

**Comment by mariolenz** [comment]
> grafana.grafana 6.0.0 is not tagged: [grafana/grafana-ansible-collection#345](https://github.com/grafana/grafana-ansible-collection/issues/345)

Seems to be tagged now 😃

**Comment by felixfontein** [comment]
cyberark.pas 1.0.31 is not tagged: https://github.com/cyberark/ansible-security-automation-collection/issues/83

**Comment by felixfontein** [comment]
grafana.grafana 6.0.0 contains `node_modules`: #540 / https://github.com/grafana/grafana-ansible-collection/issues/356

**Comment by felixfontein** [comment]
cisco.intersight 2.0.21 is not tagged: https://github.com/CiscoDevNet/intersight-ansible/issues/154

**Comment by felixfontein** [comment]
netapp.storagegrid 21.15.0 claims to have breaking changes: https://github.com/ansible-collections/netapp.storagegrid/issues/31

**Comment by felixfontein** [comment]
check_point.mgmt 6.4.1 is not tagged: https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/issues/173

**Comment by felixfontein** [comment]
ibm.storage_virtualize 3.1.0 is not tagged: https://github.com/ansible-collections/ibm.storage_virtualize/issues/74

**Comment by dbrennand** [comment]
junipernetworks.junos 11.1.0 is not tagged: https://github.com/ansible-collections/junipernetworks.junos/issues/589

**Comment by felixfontein** [comment]
junipernetworks.junos 11.1.0 does not satisfy the inclusion requirements and is a breaking change for Ansible community package users since it replaced all plugins by redirects, and added the new collection (which isn't part of Ansible) as a dependency.

**Comment by mariolenz** [comment]
According to [this comment](https://github.com/cisco-en-programmability/dnacenter-ansible/issues/327#issuecomment-4156140630) I tend to deprecate and remove `cisco.dnac`. I don't think it's a good idea to wait until `cisco.catalystcenter` has been added. At the end of the day, `cisco.dnac` has been deprecated by Cisco.

I don't like to see **officially** deprecated collections in ACP.

**Comment by felixfontein** [comment]
hitachivantara.vspone_block 4.7.0 might have breaking changes: https://github.com/hitachi-vantara/vspone-block-ansible/issues/188
(Pinned in #668)

**Comment by gotmax23** [comment]
Filed https://github.com/cyberark/ansible-security-automation-collection/issues/90

**Comment by mariolenz** [comment]
For the record:

Missing tag:

- cyberark/ansible-security-automation-collection#46
- cyberark/ansible-security-automation-collection#58
- cyberark/ansible-security-automation-collection#71
- cyberark/ansible-security-automation-collection#83

Wrongly tagged:

- cyberark/ansible-security-automation-collection#74
- see [comment in issue 83](https://github.com/cyberark/ansible-security-automation-collection/issues/83#issuecomment-2847659190)

**Comment by gotmax23** [comment]
See https://github.com/ansible-community/ansible-build-data/pull/680 and discussion in https://github.com/ansible-community/ansible-build-data/pull/679#discussion_r3266634275. We still need to file an issue with the collection maintainers.

**Comment by gotmax23** [comment]
> See [#680](https://github.com/ansible-community/ansible-build-data/pull/680) and discussion in [#679 (comment)](https://github.com/ansible-community/ansible-build-data/pull/679#discussion_r3266634275). We still need to file an issue with the collection maintainers.

Filed https://github.com/netbox-community/ansible_modules/issues/1563

**Comment by gotmax23** [comment]
Started the Removal from ansible process for cyberark.pas in https://forum.ansible.com/t/removal-from-ansible-cyberark-pas/45816

**Comment by felixfontein** [comment]
purestorage.flashblade 1.28.0 added a new dependency (everpure.flashblade >=1.27.0,<2.0.0) and replaced all its content with redirects to that collection. It also isn't tagged in the repository: #703

**Comment by felixfontein** [comment]
ibm.storage_virtualize 3.4.0 is not tagged: https://github.com/ansible-collections/ibm.storage_virtualize/issues/82

**Comment by mariolenz** [comment]
cyberark.conjur 1.13.3 is not tagged: cyberark/ansible-conjur-collection#236

**Comment by felixfontein** [comment]
Various breaking changes outside of major releases:

- https://github.com/infobloxopen/infoblox-ansible/issues/371
- https://github.com/NetApp/santricity/issues/36
- https://github.com/ansible-collections/hetzner.hcloud/issues/851
- https://github.com/ngine-io/ansible-collection-cloudstack/issues/180
